### ISSUE TITLE
Player dies too quicky

### ISSUE THREAD

**Issue by jecimovic** [tecimovic/programming-school#10]
it doesn't show the room description before you die.

**Comment by NeonScripter** [comment]
This should be configurable bc that would destroy some really cool easter eggs

**Comment by jecimovic** [comment]
like what

**Comment by NeonScripter** [comment]
like various easter eggs i have

**Comment by NeonScripter** [comment]
including the room of error in atwi80c

**Comment by NeonScripter** [comment]
and la paz

**Comment by jecimovic** [comment]
well then just do something else for it like a locked door

**Comment by NeonScripter** [comment]
and the atlantic ocean

**Comment by NeonScripter** [comment]
na not using locked door

**Comment by NeonScripter** [comment]
if you go across the atlantic ocean in a crappy boat you would die

**Comment by NeonScripter** [comment]
the more ways to die the more fun the game is

**Comment by jecimovic** [comment]
how does that affect this

**Comment by NeonScripter** [comment]
cuz it will show the la paz description while you die

**Comment by jecimovic** [comment]
so?

**Comment by NeonScripter** [comment]
please stop

**Comment by NeonScripter** [comment]
how does it affect you if this is configurable

**Comment by jecimovic** [comment]
it just does

**Comment by NeonScripter** [comment]
yeah but if its configurable its just works better

**Comment by tecimovic** [comment]
If you do `player.describeCurrentPlace()` just before you do `player.die()` it will print out the room description. So it's your choice.
