### ISSUE TITLE
Title changing

### ISSUE THREAD

**Issue by NeonScripter** [tecimovic/programming-school#13]
I would like if you could change that little thing on top of the window that says "adventure game" in atwi80c and "cellular automata" in golgoal. Is that possible?

**Comment by NeonScripter** [comment]
This could be done with something like Set title to `name` or something like that.

**Comment by tecimovic** [comment]
You can add a method "windowTitle()" to the IAdventureGame to set the window.

**Comment by tecimovic** [comment]
If you want to change the window title on the fly, you can do `player.out().setWindowTitle("new title")`
