### ISSUE TITLE
Key per door

### ISSUE THREAD

**Issue by NeonScripter** [tecimovic/programming-school#3]
Some rooms the player needs to carry a specific object to enter

For example:

A player can't enter the guinea pig room, but when the player carries a guinea pig, they can enter it.

**Comment by jecimovic** [comment]
i thought that was my idea

**Comment by jecimovic** [comment]
i really need that feature for my adventure game

**Comment by tecimovic** [comment]
I propose we do this:

Add an API:
  room.addLockedDirection("text", destinationRoom, keyObject);

This way, the engine allows you to go to the detinationRoom ONLY if you have keyObject.

Would that work?

**Comment by NeonScripter** [comment]
Good! It was added! Works as intended.
